---
  - name: Installing / Updating Asterisk on Debian systems
    apt: >-
      pkg=asterisk
      force=yes
      state=latest
    tags: asterisk
    when: ansible_os_family == 'Debian'

  - name: Installing / Updating Asterisk on RedHat systems
    yum: >-
      pkg=asterisk
      state=latest
    tags: asterisk
    when: ansible_os_family == 'RedHat'
